name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clone Foundry repository
        run: |
          if [ ! -d "foundry" ]; then
            git clone --branch feat/single_json_output https://github.com/BuildBearLabs/foundry.git
          fi
        shell: bash

      - name: Set Foundry commit hash
        id: foundry_hash
        run: echo "hash=$(git -C foundry rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Restore Foundry build cache
        uses: actions/cache@v3
        id: cache-foundry
        with:
          path: |
            foundry/target
            $HOME/.config/.foundry/bin
          key: ${{ runner.os }}-foundry-build-${{ steps.foundry_hash.outputs.hash }}

      - name: Build Foundry from source or copy from target
        run: |
          FOUNDRY_BIN="$HOME/.config/.foundry/bin/forge"
          TARGET_FORGE="foundry/target/release/forge"

          mkdir -p "$(dirname "$FOUNDRY_BIN")"

          if [ -f "$FOUNDRY_BIN" ]; then
            echo "✅ Forge binary found in bin path, skipping build."
          elif [ -f "$TARGET_FORGE" ]; then
            echo "✅ Forge binary found in target/release, copying to bin."
            cp "$TARGET_FORGE" "$FOUNDRY_BIN"
          else
            echo "❌ Forge binary not found, building from source..."
            cd foundry
            cargo b -r
            cp target/release/forge "$FOUNDRY_BIN"
          fi

          echo "$(dirname "$FOUNDRY_BIN")" >> $GITHUB_PATH

      - name: Save Foundry build cache
        if: steps.cache-foundry.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            foundry/target
            $HOME/.config/.foundry/bin
          key: ${{ runner.os }}-foundry-build-${{ steps.foundry_hash.outputs.hash }}

      - name: Show Forge version
        run: forge --version

      - name: Run Test
        run: forge test --allow-failure

      - name: test_ci
        uses: BuildBearLabs/buildbear_x_action@0b837ff37a35acc6f70d07faa59d5cf6c913397c
        with:
          buildbear-api-key: "2c4a6a01-eb1a-46cd-8df8-6953c343728b"
        env:
          BUILDBEAR_BASE_URL: "${{ secrets.BUILDBEAR_BASE_URL }}"
